### PR TITLE
#7 - Adds json schema support;

### PR DESCRIPTION
**Pull request by marcelojaloto**
Review the proposed solution.

### CODE REVIEW

**Comment by geoffsmith82** [comment]
Just want to add, I believe swagger 2.0 only supports a subset of json-schema.  Openapi 3.0, I believe supports a complete version of it ... as at a particular draft level.

**Comment by marcelojaloto** [comment]
We can upgrade to Swagger 3.0 while maintaining compatibility with version 2.0. However, version 2.0 already meets the great majority regarding the JSON schema. We are open to receiving new collaborations to migrate to version 3.0.

**Review by cunhaw — APPROVED** [review]
Great code!
Suggestion: some usage examples.

**Comment by marcelojaloto** [comment]
Thanks!

**Pull request merged**
